# Generated by Django 5.1.6 on 2026-02-18 05:54

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tradehub", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="amount",
            field=models.DecimalField(
                decimal_places=10, default=Decimal("0"), max_digits=50
            ),
        ),
    ]
