# Generated by Django 5.1.6 on 2026-02-18 07:24

import autoslug.fields
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tradehub", "0002_alter_asset_amount"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="asset",
            options={
                "ordering": ["-id"],
                "verbose_name": "Asset",
                "verbose_name_plural": "Assets",
            },
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["name"], "verbose_name_plural": "Categories"},
        ),
        migrations.AlterField(
            model_name="asset",
            name="amount",
            field=models.DecimalField(
                decimal_places=10,
                default=Decimal("0"),
                help_text="Current quantity held (e.g., 0.5 for Bitcoin)",
                max_digits=50,
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="category",
            field=models.ForeignKey(
                blank=True,
                help_text="Asset category (Crypto, Stocks, etc.)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tradehub.category",
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="cost",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                help_text="Total cost basis in USD",
                max_digits=100,
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="logs",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="JSON array of transaction logs with buy/sell records",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="name",
            field=models.CharField(
                help_text="Asset name (e.g., Bitcoin, Apple Inc., US Treasury Bonds)",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="ort_usd",
            field=models.DecimalField(
                decimal_places=10,
                default=Decimal("0"),
                help_text="Current market value in USD (ORT = average price)",
                max_digits=100,
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                blank=True,
                editable=False,
                help_text="Auto-generated unique identifier",
                null=True,
                populate_from="generate_random_slug",
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="user",
            field=models.ForeignKey(
                help_text="User who owns this asset",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                help_text="Category name (e.g., Cryptocurrency, Stocks)",
                max_length=1000,
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="URL-friendly identifier (auto-generated from name)",
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="asset",
            unique_together={("user", "name", "category")},
        ),
    ]
